# Generated by Django 4.0.6 on 2022-09-12 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deposit_address',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='VNI', max_length=50)),
                ('dark_mode', models.BooleanField(default=False)),
                ('deposit_address', models.TextField(blank=True, default=None, null=True)),
                ('email_when_follows', models.BooleanField(default=True)),
                ('email_when_hit_sl_tp', models.BooleanField(default=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
