# Generated by Django 4.0.6 on 2022-09-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_deposit_address_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='information',
        ),
    ]
