# Generated by Django 4.0.6 on 2022-09-13 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_bio_user_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 13, 6, 25, 29, 15868, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='deposit_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
