# Generated by Django 4.0.6 on 2022-09-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_settings_created_date_alter_settings_deposit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_when_follows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_when_hit_sl_tp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='VNI', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
