# Generated by Django 4.0.6 on 2022-09-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_favorite_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deposit_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_when_follows',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_when_hit_sl_tp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_coins',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_coins', to='api.favoritecoin'),
        ),
    ]
