# Generated by Django 4.0.6 on 2022-09-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_dark_mode_remove_user_deposit_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deposit_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_when_follows',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_when_hit_sl_tp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='VNI', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
